### PR TITLE
Automatic cleanup!

### PR DESCRIPTION
**Pull request by rictic**

### CODE REVIEW

**Comment by cdata** [comment]
Tests fail in MS Edge for undetermined reasons https://github.com/PolymerElements/iron-resizable-behavior/issues/12

**Comment by notwaldorf** [comment]
This looks like it's passing on master...maybe it needs a rebase?

**Comment by cdata** [comment]
@notwaldorf It's probably passing on master because of lack of ShadowDOM tests ;)

**Comment by rictic** [comment]
Ha, jinx! 

I just rebased from master and git says that it's up to date, so I think this test break is real.

**Comment by notwaldorf** [comment]
@cdata nooooo i had run them locally and stuff.

@rictic i vote to evict edge from the big brother house.

**Comment by notwaldorf** [comment]
I'm going to merge this, and open a PR that the tests are borked.

**Pull request merged**
